export const ICONS_NAME = {
  SHOPPING_BAG: "SHOPPING_BAG",
  LOGIN_BOX: "LOGIN_BOX",
  LIKE_EMPTY: "LIKE_EMPTY",
  LIKE_FILL: "LIKE_FILL",
  LIKE_COLOR: "LIKE_COLOR",
  USER: "USER",
  COMMENT: "COMMENT",
  LEFT_CIRCLE: "LEFT_CIRCLE",
  RIGHT_CIRCLE: "RIGHT_CIRCLE",
  LEFT_OUTLINE: "LEFT_OUTLINE",
  RIGHT_OUTLINE: "RIGHT_OUTLINE",
} as const;
